name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Test and Push
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt

      - name: Display versions
        run: |
          java -version
          scala -version
          sbt --version

      - name: Launch tests
        working-directory: .
        run: sbt -v test

      - name: Push to Repository
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          NEXUS_CREDENTIALS: ${{ secrets.NEXUS_CREDENTIALS }}
        run: |
          echo "$NEXUS_CREDENTIALS" > nexus.sbt
          sbt publish
