name: CI/CD

on:
  pull_request:
    - opened

jobs:
  ci:
    name: Test and Push
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt

      - name: Display versions
        run: |
          java -version
          sbt --version

      - name: Set Nexus credentials
        working-directory: .
        run: |
          echo "${{ secrets.NEXUS_CREDENTIALS }}" | base64 -d > ~/.sbt/.credentials_sml_nexus

      - name: Check formatting
        working-directory: .
        run: sbt scalafmtCheckAll

      - name: Launch tests
        working-directory: .
        run: sbt -v test

      - name: Push to Repository
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          sbt publish

      - name: Log in to Azure ACR
        if: github.ref == 'refs/heads/master'
        uses: azure/docker-login@v1
        with:
          login-server: smlacademyacr.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: sbt docker:publish
