name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Test and Push
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt

      - name: Display versions
        run: |
          java -version
          sbt --version

      - name: Launch tests
        working-directory: .
        run: sbt -v test

      - name: Push to Repository
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          echo "${{ secrets.NEXUS_CREDENTIALS }}" | base64 -d > ~/.sbt/.credentials_sml_nexus
          sbt publish

      - name: Log in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          az account show
          az acr login -n smlacademyacr
          az acr list
