name: CI/CD

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - ready_for_review
      - reopened
      - unlocked
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write # for version tagging

jobs:
  ci:
    name: Test and Push
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.pusher.name, 'softwaremill-ci') }}

    steps:
      - name: Display GitHub Events
        run: |
          echo "Commit author: ${{ github.event.pusher.name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHA_SML_CI_PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt

      - name: Display versions
        run: |
          java -version
          sbt --version

      - name: Set Nexus credentials
        working-directory: .
        run: |
          echo "${{ secrets.NEXUS_CREDENTIALS }}" | base64 -d > ~/.sbt/.credentials_sml_nexus

      - name: Check formatting
        working-directory: .
        run: sbt scalafmtCheckAll

      - name: Launch tests
        working-directory: .
        run: sbt -v test

      # - name: Log in to Azure ACR
      #   if: github.ref == 'refs/heads/master'
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: smlacademyacr.azurecr.io
      #     username: ${{ secrets.ACR_USER }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      - name: Release to Nexus # and ACR
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          git config --local user.name "sbt-release"
          git config --local user.email "sbt-release"
          sbt "release with-defaults"
